<div class="alert alert-block bg-primary">
<center>MÉTODOS NUMÉRICOS</center>
<center>LISTA 07</center>
<center>ALUNA: MARIA LUÍZA TEIXEIRA NASCIMENTO</center>
</div>

In [1]:
import pandas as pd
import numpy as np
import scipy.linalg as sla

<div class="alert alert-block alert-info">
<center><strong>Exercício 1:</strong> 
    <p>Implemente uma função que use eliminação gaussiana com pivotamento parcial para encontrar o vetor solução de um sistema de equações lineares.</p>
    <p>Essa função terá de contemplar as duas etapas do processo: a eliminação, cujo algoritmo é discutido no notebook das aulas da semana, e que terá como saída a matriz escalonada e a substituição retroativa, que encontrará a solução do sistema triangular superior obtido do escalonamento, e cuja implementação já foi feita por vocês em exercício anterior.</p>
    <p>Para testar e verificar se a função de vocês está corretamente implementada, compare os resultados
    com a função solve da biblioteca Scipy, cujo uso também foi discutido no notebook, para os seguintes
    exemplos de sistemas:</p>
    </center>
</div>

In [2]:
#Função Triangular Superior: 
def sist_lin_tri_sup(M_coeficientes, Termos_ind):
  n = len(Termos_ind)
  x = np.empty(n)
  x[-1] = Termos_ind[-1]/M_coeficientes[-1, -1]
  for i in range(n-2, -1, -1):
    x[i] = (Termos_ind[i] - np.sum(M_coeficientes[i, i+1:] * x[i+1:]))/M_coeficientes[i,i]
  return x

In [3]:
#Função pivôteamento parcial:
def PivotamentoParcial(A_b, i):
  pivoMax = np.abs(A_b[i:,i]).argmax() + i
  A_b[[pivoMax, i]] = A_b[[i, pivoMax]]
  return A_b

In [4]:
#Função Eliminação Simples:
def EliminacaoSimples(M_coeficientes, Termos_ind):
  A_b = np.c_[M_coeficientes, Termos_ind]
  for i in range(len(M_coeficientes) - 1):
    for j in range(i + 1, len(M_coeficientes)):
      A_b[j] = A_b[j] - (A_b[i, j] / A_b[i, i]) * A_b[i]
  return A_b[:, : -1], A_b[:, -1]

In [5]:
#Função Eliminação com Pivoteamento:
def EliminacaoPivotamento(M_coeficientes, Termos_ind) :
    A_b = np.c_[M_coeficientes, Termos_ind]
    for i in range(len(M_coeficientes) - 1) :
        A_b = PivotamentoParcial(A_b, i)
        for j in range(i + 1, len(M_coeficientes)) :
            A_b[j] = A_b[j] - (A_b[j, i] / A_b[i, i]) * A_b[i]
    return A_b[:, : -1], A_b[:, -1]

<div class="alert alert-block alert-info">
<strong>Letra A</strong><br>
<p>$1x_1 + 1x_2 + 1x_3 = 1$</p>
<p>$4x_1 + 4x_2 + 2x_3 = 2$</p>
<p>$2x_1 + x_2 - x_3 = 0$</p>
</div>

In [6]:
A = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
B = np.array([1, 2, 0])

In [7]:
print(EliminacaoSimples(A, B))
_A, _B = EliminacaoSimples(A, B)

(array([[ 1,  1,  1],
       [ 3,  3,  1],
       [ 0, -1, -2]]), array([ 1,  1, -1]))


In [8]:
print(sist_lin_tri_sup(_A, _B))

[0.33333333 0.16666667 0.5       ]


In [9]:
print(sla.solve(A, B))

[ 1. -1.  1.]


<div class="alert alert-block alert-info">
<strong>Letra B</strong><br>
<p>$7x_1 - 7x_2 + 1x_3 = 1$</p>
<p>$-3x_1 + 3x_2 + 2x_3 = 2$</p>
<p>$7x_1 + 7x_2 - 72x_3 = 7$</p>
</div>

In [10]:
C = np.array([[7, -7, 1], [-3, 3, 2], [7, 7, -72]])
D = np.array([1, 2, 7])

In [11]:
print(EliminacaoSimples(C, D))
_C, _D = EliminacaoSimples(C, D)

(array([[  7,  -7,   1],
       [  4,  -4,   3],
       [  9,   5, -69]]), array([1, 3, 8]))


In [12]:
print(sist_lin_tri_sup(_C, _D))

[-0.67753623 -0.83695652 -0.11594203]


In [13]:
print(sla.solve(C, D))

[5.64285714 5.64285714 1.        ]


<div class="alert alert-block alert-info">
<strong>Letra C</strong><br>
<p>$1x_1 + 2x_2 + 3x_3 + 4X_4 = 20$</p>
<p>$2x_1 + 2x_2 + 3x_3 + 4X_4 = 22$</p>
<p>$3x_1 + 3x_2 + 3x_3 + 4X_4 = 22$</p>
<p>$4x_1 + 4x_2 + 4x_3 + 4X_4 = 24$</p>
</div>

In [14]:
E = np.array([[1, 2, 3, 4], [2, 2, 3, 4], [3, 3, 3, 4], [4, 4, 4, 4]])
F = np.array([20, 22, 22, 24])

In [15]:
print(EliminacaoSimples(E, F))
_E, _F = EliminacaoSimples(E, F)

(array([[ 1,  2,  3,  4],
       [ 0, -2, -3, -4],
       [ 0,  0, -1, -2],
       [ 0,  0,  0,  0]]), array([ 20, -18, -11,   2]))


In [16]:
print(sist_lin_tri_sup(_E, _F))

[ nan  nan -inf  inf]


C:\Users\Patrícia Nascimento\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in long_scalars
  """
C:\Users\Patrícia Nascimento\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [17]:
print(sla.solve(E, F))

[ 2. -2.  2.  4.]


<div class="alert alert-block alert-light">
    <center><strong>Explicações não  são necessárias, pois o métdodo está bem auto explicativo</strong></center>
</div>